# # -- 코드를 작성해주세요
SELECT B.YEAR AS YEAR,
    (B.MAX_SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV,
    A.ID
FROM ECOLI_DATA AS A
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
      MAX(SIZE_OF_COLONY) AS MAX_SIZE
      FROM ECOLI_DATA
      GROUP BY YEAR) AS B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV

# -- 코드를 작성해주세요
# SELECT *
# FROM ECOLI_DATA AS A
# JOIN (SELECT DIFFERENTIATION_DATE,
#       MAX(SIZE_OF_COLONY) AS MAX_SIZE
#       FROM ECOLI_DATA
#       GROUP BY DIFFERENTIATION_DATE) AS B
# ON A.DIFFERENTIATION_DATE = B.DIFFERENTIATION_DATE
# ORDER BY YEAR, YEAR_DEV