-- 코드를 입력하세요
SELECT DISTINCT(FIRST_HALF.FLAVOR) AS FLAVOR
FROM FIRST_HALF
LEFT JOIN ICECREAM_INFO
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE FIRST_HALF.TOTAL_ORDER > 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC